version: '3'
services:
  app:
    container_name: basedash-app
    image: basedash/basedash
    depends_on:
      - db
    env_file: ./docker.env
    ports:
      - "5000:5000"
  db:
    container_name: basedash-db
    image: basedash/db
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    ports:
      - '5432:5432'
    env_file: ./docker.env
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
